config/routes.rb
Rails.application.routes.draw do
  get '/categories/home' => 'categories#home'
  root :to => 'categories#home'


  post '/items/nearme' => 'items#nearme'
  get '/items/filter' => 'items#filter'

  get '/categories/api' => 'categories#api'
  get '/bookmarks/api' => 'bookmarks#api' 
  get '/items/api' => 'items#api'

  post '/buy/:id', to: 'transactions#create', as: :buy
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

  resources :wishes

  resources :bookmarks

  resources :items do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  
  resources :categories do 
    collection do
      get 'search'
    end
  end

  resources :subcategories
  get "mailbox/api" => "mailbox#api"
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
      member do
          post :reply
          post :trash
          post :untrash
      end
  end
  get '/session' => 'session#show'
  get '/login' => 'session#new'
  get '/session' => 'session#show'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  
  resources :users


  
end

app/models/wish.rb
# == Schema Information
#
# Table name: wishes
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  category_id    :integer
#  subcategory_id :integer
#  name           :string
#  item_id        :integer
#  present        :boolean          default(FALSE)
#  created_at     :datetime
#  updated_at     :datetime
#

class Wish < ActiveRecord::Base
	belongs_to :user
	belongs_to :subcategory
	has_one :item
	
	validates :name, :presence => true
	validates :category_id, :presence => true
	validates :subcategory_id, :presence => true


end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :edit, :update, :destroy]

  # GET /wishes
  # GET /wishes.json
  def index
    @wishes = @current_user.wishes
  end

  # GET /wishes/1
  # GET /wishes/1.json
  def show
    @bookmark=Bookmark.new

  end

  # GET /wishes/new
  def new
    @wish = Wish.new
  end

  # GET /wishes/1/edit
  def edit
  end

  # POST /wishes
  # POST /wishes.json
  def create
    @wish = Wish.new(wish_params)

    respond_to do |format|
      if @wish.save
        format.html { redirect_to @wish, notice: 'Wish was successfully created.' }
        format.json { render :show, status: :created, location: @wish }
      else
        format.html { render :new }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end

    @current_user.wishes << @wish
  end

  # PATCH/PUT /wishes/1
  # PATCH/PUT /wishes/1.json
  def update
    respond_to do |format|
      if @wish.update(wish_params)
        format.html { redirect_to @wish, notice: 'Wish was successfully updated.' }
        format.json { render :show, status: :ok, location: @wish }
      else
        format.html { render :edit }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1
  # DELETE /wishes/1.json
  def destroy
    @wish.destroy
    respond_to do |format|
      format.html { redirect_to wishes_url, notice: 'Wish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish
      @wish = Wish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wish_params
      params.require(:wish).permit(:user_id, :subcategory_id, :category_id, :name)
    end
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/wishes/_form.html.erb
<div class="item">
  

<% if @current_user.present? %>


  <%= form_for(@wish) do |f| %>
    <% if @wish.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

        <ul>
        <% @wish.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="row">
    <div class="col-md-3"></div>
      <div class="form-group col-md-6">
        <%= f.label :category_id, 'Category' %>
        <%= f.select :category_id, Category.all.map{|category| ["#{category.name}", category.id]}, :include_blank => true %>
        <%= f.label :subcategory_id, 'Subcategory' %>
        <%= f.select :subcategory_id, Subcategory.all.map{|subcategory| ["#{subcategory.category.name}: #{subcategory.name}", subcategory.id]}, :include_blank => true %>
      </div>
    </div>


    <div class="row">
      <div class="col-md-3"></div>
      <div class="form-group col-md-6">
        <%= f.label :name, :class => 'sr-only', :for => 'exampleWishName3' %>
        <%= f.text_field :name, :class => 'form-control', :id => 'exampleWishName3', :placeholder => 'Item Name' %>
      </div>
    </div>
    
    
    <div class="actions">
     <div class="col-md-3"></div>
      <p><%= submit_tag "Make a Wish", :class => 'btn btn-default' %></p>
    </div>
  <% end %>

<% else %>
  <p>You need to have an account to add to your wish list.</p>
  <p>Please <%= link_to 'Sign In', root_path %>, or <%= link_to 'Create an Account', new_user_path %>.</p>
<% end %>
</div>

app/views/wishes/edit.html.erb
<h1>Editing Wish</h1>

<%= render 'form' %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', wishes_path %>

app/views/wishes/index.html.erb
<p id="notice"><%= notice %></p>


  <h2><%= @current_user.name %>'s Wishes</h2>



<% @wishes.each do |wish| %>
    <ul>
      <li>
        Wish: <%= link_to wish.name, wish %>
      </li>
    </ul>
    

<% end %>
  

<br>

<%= link_to 'Make A Wish', new_wish_path %>

app/views/wishes/new.html.erb
<div class="category-holder">
	<h2>Make A Wish</h2>
</div>

<%= render 'form' %>

app/views/wishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Wish:</strong>
  	<%= @wish.name %>
</p>

<p id="wishID">
	<strong>ID:</strong>
	<%= @wish.id %>
</p>

<p>
  	<strong>Category:</strong>
  	<%= @wish.subcategory.category.name %>
</p>


<p>
  	<strong>Subcategory:</strong>
  	<%= @wish.subcategory.name %>
</p>


<p>
	<strong>Created:</strong>
	<%= @wish.created_at.strftime "%e %B, %Y" %>
</p>

<ul class = "wishparent">
	<li class="bookmarkpost"> 

		<%= form_for(@bookmark) do |f| %>
			<div class="field">
			   <br>
			    <%= f.hidden_field :user_id, :value => @wish.user_id %>
		 	</div>
		    <div class="field">
			    <br>
			    <%= f.hidden_field :item_id, :value => @wish.item_id %>
		  	</div>
		  	<div class="bookawish">
		    	<%= f.submit%>
		 	</div>
		<% end %>

	</li>

	<li class="wishdelete"> <%= link_to 'Crush', @wish, :method => 'delete', target: "_blank", id: "wishdelete" %> </li>
</ul>



<%= link_to 'Edit', edit_wish_path(@wish) %> |
<%= link_to 'My Wishes', wishes_path %> |
<%= link_to 'Crush', @wish, :method => 'delete', :data => {:confirm => "Are you sure you want to turn your wish into dust? That's very existential..."} %>

<%# link_to 'Create Bookmark', new_bookmark_path{:controller => "create", :method => 'post',@wish}%>

<!-- 	<%= button_to 'post bookmark', {:controller => "bookmarks", :action => "create", :user_id => @wish.user_id, :item_id=> @wish.item_id} , :method=>:post , id: "bookawish" %> -->