config/routes.rb
Rails.application.routes.draw do
  get '/categories/home' => 'categories#home'
  root :to => 'categories#home'


  post '/items/nearme' => 'items#nearme'
  get '/items/filter' => 'items#filter'

  get '/categories/api' => 'categories#api'
  get '/bookmarks/api' => 'bookmarks#api' 
  get '/items/api' => 'items#api'

  post '/buy/:id', to: 'transactions#create', as: :buy
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

  resources :wishes

  resources :bookmarks

  resources :items do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  
  resources :categories do 
    collection do
      get 'search'
    end
  end

  resources :subcategories
  get "mailbox/api" => "mailbox#api"
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
      member do
          post :reply
          post :trash
          post :untrash
      end
  end
  get '/session' => 'session#show'
  get '/login' => 'session#new'
  get '/session' => 'session#show'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  
  resources :users


  
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id                  :integer          not null, primary key
#  name                :string
#  price               :integer
#  subcategory_id      :integer
#  user_id             :integer
#  category_id         :integer
#  image               :string
#  description         :string
#  created_at          :datetime
#  updated_at          :datetime
#  private_room        :string
#  private_bathroom    :string
#  rooms               :integer
#  bathrooms           :integer
#  parking             :string
#  laundry             :string
#  rent                :integer
#  sale_price          :integer
#  housing_type        :string
#  area                :integer
#  available           :date
#  openhouse1          :datetime
#  openhouse2          :datetime
#  openhouse3          :datetime
#  pets                :boolean
#  furnished           :boolean
#  smoking             :boolean
#  wheelchair          :boolean
#  employment_type     :string
#  salary              :string
#  recruiter           :boolean
#  internship          :boolean
#  non_profit          :boolean
#  telecommuting       :boolean
#  disability          :boolean
#  make                :string
#  condition           :string
#  make_type           :string
#  dimensions          :string
#  serial_number       :string
#  engine_hours        :integer
#  length_overall      :integer
#  propulsion_type     :string
#  make_year           :integer
#  vin                 :string
#  cylinders           :string
#  drive               :string
#  fuel                :string
#  engine_displacement :string
#  paint_colour        :string
#  size                :string
#  title_status        :string
#  transmission        :string
#  car_type            :string
#  media_type          :string
#  mobile_os           :string
#  garage_sale1        :date
#  garage_sale2        :date
#  garage_sale3        :date
#  start_time          :time
#  odometer            :integer
#  event               :datetime
#  tickets             :integer
#  venue               :string
#  sale_id             :integer
#  latitude            :float
#  longitude           :float
#  address             :string
#
class Item < ActiveRecord::Base
	searchkick text_start: [:name, :description], suggest: ["name"]
	def search_data 
		{
			name: name,
			description: description
		}
	end	

	belongs_to :user
	belongs_to :subcategory
	has_one :bookmark
	belongs_to :sale

	validates :name, :presence => true
	validates :description, :presence => true
	validates :subcategory_id,  :presence => true


	

	# validates_numericality_of :price,
	# greater_than: 49, message: "must be atleast 50 cents" 

	# geocoded_by :full_street_address   # can also be an IP address
	# after_validation :geocode          # auto-fetch coordinates

	reverse_geocoded_by :latitude, :longitude
	# after_validation :reverse_geocode  

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

 

  def search 
    query = params[:search].presence || "*" 
    # @sub_categories = Subcategory.search query , suggest: true
    @items = Item.search query , suggest: true
    
    @items.each_with_index do |model, i|

      unless model.address.nil? || model.address[0..5] == '1 hour'
        if i % 10 == 0
          sleep(2)
        end
        coordinates =  Geocoder.coordinates(model.address)

        lati = coordinates[0]
        longi = coordinates[1]
      end
       Intermediary.create name: model.name, latitude: lati, longitude: longi, item_id: model.id, address: model.address

    end

  end

   def nearme

        distance_from_user = params[:distance_from]
        
        flash[:filterlist] = Intermediary.near([@current_user.longitude, @current_user.latitude], distance_from_user)
        redirect_to items_filter_path
   end

   def filter
    # raise "hello"
     @listofitems = flash[:filterlist]
     render :filter

     destructor
   end

  def destructor
    Intermediary.destroy_all
  end

  def autocomplete
    render json: Item.search(params[:term], fields: [{name: :text_start, description: :text_start}], limit: 20).map(&:name)
  end
  # GET /items
  # GET /items.json
  def index
    @items = @current_user.items
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  def api 
    @items = Item.all
    render json: @items
  end

  # POST /items
  # POST /items.json
  def create
 
    if params[:file] == nil
      item_details = item_params
      item_details[:image] = 'http://fillmurray.com/200/200'

    else
      response = Cloudinary::Uploader.upload params[:file]
      item_details = item_params
      item_details[:image] = response["url"]
    end


    @item = Item.create item_details
    

    allWishes = Wish.all.each do |eachWish|
      
      if(eachWish.category_id == Item.last.category_id && eachWish.subcategory_id == Item.last.subcategory_id && eachWish.name == Item.last.name)
        Wish.update eachWish.id, item_id: Item.last.id
      end
    end

    if @item.category_id == 1
      #if the category is community
      @item.price = 0
    
    elsif @item.category_id == 4
      #if the category is personals
      @item.price = 0
    
    elsif @item.category_id == 6
     #if the category is housing
     @item.price = 0 

    else
      @item.price
    
    end

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
        
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end


    @current_user.items << @item

  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end


  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def findme
    Item.near([@current_user.latitude, @current_user.longitude],params(:distance))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params


      params.require(:item).permit(:name, :price, :subcategory_id, :user_id, :description, :category_id, :image, :rooms, :private_room, :bathrooms, :parking, :laundry, :rent, :housing_type, :area, :available, :openhouse1, :openouse2, :openhouse3, :pets, :rooms, :bathrooms, :furnished, :smoking, :wheelchair, :sale_price, :employment_type, :salary, :recruiter, :internship, :non_profit, :telecommuting, :disability, :make, :model, :condition, :dimensions, :serial_number, :engine_hours, :length_overall, :propulsion_type, :model_year, :vin, :cylinders, :drive, :fuel, :engine_displacement, :paint_colour, :size, :title_status, :transmission, :car_type, :media_type, :mobile_os, :garage_sale1, :garage_sale2, :garage_sale3, :start_time, :odometer, :event, :tickets, :venue, :latitude, :longitude, :address)

    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="item">
  <% if @current_user.present? %>


  <%= form_for @item,:html => { :multipart => true } do |f| %>
    <% if @item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="row">
      <div class="col-md-3"></div>
      <div class="form-group col-md-6">
        <%= f.label :category_id, 'Category' %>
        <%= f.select :category_id, Category.all.map{|category| ["#{category.name}", category.id]}, :include_blank => true %>
        <%= f.label :subcategory_id, 'Subcategory' %>
        <%= f.select :subcategory_id, Subcategory.all.map{|subcategory| ["#{subcategory.category.name}: #{subcategory.name}", subcategory.id]}, :include_blank => true %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-3"></div>
      <div class="form-group col-md-6">
        <%= f.label :name, :class => 'sr-only', :for => 'exampleInputName3' %>
        <%= f.text_field :name, :class => 'form-control', :id => 'exampleInputName3', :placeholder => 'Item Name' %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-3"></div>
      <div class="form-group col-md-6">
        <%= f.label :description, :class => 'sr-only', :for => 'exampleInputDescription3' %>
        <%= f.text_area :description, :class => 'form-control', :id => 'exampleInputDescription3', :placeholder => 'Description' %>
      </div>
    </div>

    <div id="further-info" class="row">
      <div class="col-md-3"></div>
      <div id="for_sale"><%= render 'for_sale', :f => f %></div>
      <div id="housing"><%= render 'housing', :f => f %></div>
      <%# :f => f will allow other rendered forms to be associated with the main form %>
      <div id="jobs"><%= render 'jobs', :f => f %></div>
      
    </div>
    
    <div class="row">
      <div class="form-group">
        <div class="col-md-3"></div>
        <%= f.cl_image_upload :file %>
      </div>
    </div>
    
    <div class="form-group col-md-6">
        <%= f.hidden_field :latitude, value: @current_user.latitude %>
    </div>
    
    <div class="form-group col-md-6">
        <%= f.hidden_field :longitude, value: @current_user.longitude %>
    </div>

    <div class="form-group col-md-6">
        <%= f.hidden_field :address, value: @current_user.address %>
    </div>

    <div class="row">
      <div class="form-group">
        <p><%= submit_tag "Post", :class => 'btn btn-default' %></p>
      </div>
    </div>
    
    


  <% end %>
  

<% else %>

<p>You need to have an account to post.</p>
<p>Please <%= link_to 'Sign In', login_path %>, or <%= link_to 'Create an Account', new_user_path %>.</p>

<% end %>

</div>

app/views/items/_housing.html.erb
<div class="further-info">
	<div class="row">
		<div id="rent" class="form-group col-md-3">
		<%= f.label :rent, :class => 'sr-only', :for => 'exampleInputRent3' %>
		<%= f.number_field :rent, :class => 'form-control', :id => 'exampleInputRent3', :placeholder => 'Rent ($) per week', :min => 0 %>
		</div>

		<div id="sale" class="form-group col-md-3">
		<%= f.label :sale_price, :class => 'sr-only', :for => 'exampleInputSale3' %>
		<%= f.number_field :sale_price, :class => 'form-control', :id => 'exampleInputSale3', :placeholder => 'Sale Price ($)', :min => 0 %>
		</div>
		
		<div class="form-group col-md-3">
		<%= f.label :area, :class => 'sr-only', :for => 'exampleInputArea3' %>
		<%= f.number_field :area, :class => 'form-control', :id => 'exampleInputArea3', :placeholder => 'Area (m2)', :min => 0 %>
		</div>
	</div>
	<div id="housing"class="row">
		<div class="col-md-3"></div>
		<div class="form-group col-md-2">
			<%= f.label :rooms, 'Room(s)', :id => 'exampleInputRoom3' %>
			<%= f.number_field :rooms, :class => 'form-control', :id => 'exampleInputRoom3', :min => 0 %>
		</div>
		<div class="form-group col-md-2">
			<%= f.label :bathrooms, 'Bathroom(s)', :id => 'exampleInputBathroom3' %>
			<%= f.number_field :bathrooms, :class => 'form-control', :id => 'exampleInputBathroom3', :min => 0 %>
		</div>
		<div class="form-group col-md-2">
			<%= f.label :available, 'Available From' %>
			<%= f.date_field :available, :class => 'form-control', :min => Date.today %>
		</div>
	</div>
	<div id="housing_description" class="row">
		<div class="col-md-2"></div>
		<div id="housing_type" class="col-md-1">
			<%= f.label :housing_type, 'Type' %>
			<%= f.select :housing_type, options_for_select(['apartment', 'cottage', 'duplex', 'house', 'loft', 'townhouse', 'unit']), :include_blank => true %>
		</div>
		
		
		<div id="shared" class="col-md-2">
			<%= f.label :private_room, 'Private Room' %>
			<%= f.select :private_room, options_for_select(['private room', 'room not private']), :include_blank => true %>
		</div>
		<div id="shared" class="col-md-2">
			<%= f.label :private_bathroom %>
		<%= f.select :private_bathroom, options_for_select(['private bathroom', 'bathroom not private']), :include_blank => true %>
		</div>
		
		<div class="col-md-1">
			<%= f.label :laundry, 'Laundry' %>
			<%= f.select :laundry, options_for_select(['w/d in unit', 'laundry in building', 'laundry on site', 'w/d hookups', 'no laundry on site' ]), :include_blank => true %>
		</div>
		<div class="col-md-1"></div>
		<div class="col-md-1">
			<%= f.label :parking, 'Parking' %>
			<%= f.select :parking, options_for_select(['carport', 'attached garage', 'detached garage', 'off-street parking', 'street parking', 'valet parking', 'no parking']), :include_blank => true %>
		</div>
		
	</div>
	<div id="housing_checkboxes" class="row">
		<div class="col-md-3"></div>
		<table id="housing-table" class="table table-striped">
			<tr>
				<th><%= f.label :pets, 'Pets Allowed'%></th>
				<th><%= f.label :furnished, 'Furnished' %></th>
				<th><%= f.label :smoking, 'Smoking' %></th>
				<th><%= f.label :wheelchair, 'Wheelchair Accessible' %></th>
			</tr>
			<tr>
				<td><%= f.check_box :pets %></td>
				<td><%= f.check_box :furnished %></td>
				<td><%= f.check_box :smoking %></td>
				<td><%= f.check_box :wheelchair %></td>
			</tr>
		</table>	
	</div>
	<div id="openhouse" class="row">
		<div class="col-md-3"></div>
		<div class="form-group col-md-5">
			<%= f.label :openhouse1, 'Open for inspection' %>
			<%= f.datetime_select :openhouse1, :class => 'form-control', :include_blank => true %>
		</div>
	</div>
	<div id="openhouse" class="row">
		<div class="col-md-3"></div>
		<div class="form-group col-md-5">
			<%= f.label :openhouse2, 'Open for inspection' %>
			<%= f.datetime_select :openhouse2, :class => 'form-control', :include_blank => true %>
		</div>

	</div>
	<div id="openhouse" class="row">
		<div class="col-md-3"></div>
		<div class="form-group col-md-5">
			<%= f.label :openhouse3, 'Open for inspection' %>
			<%= f.datetime_select :openhouse3, :class => 'form-control', :include_blank => true %>
		</div>
	</div>

</div>

app/views/items/_jobs.html.erb
<div class="further-info">
	<div class="row">
		<div id="employment_type" class="col-md-2">
			<%= f.label :employment_type, 'Employment Type' %>
			<%= f.select :employment_type, options_for_select(["full-time", "part-time", "casual", "contract", "employee's choice"]), :include_blank => true %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-1"></div>
			<table class="table table-striped">
				<tr>
					<th>
						<%= f.label :recruiter, 'Direct Contact by Recruiters is Okay'%>
					</th>
					<th>
						<%= f.label :internship, 'Internship' %>
					</th>
					<th>
						<%= f.label :non_profit, 'Non-profit Organisation' %>
					</th>
					<th>
						<%= f.label :telecommuting, 'Telecommuting Permissible' %>
					</th>
					<th>
						<%= f.label :disability, 'Open for People with Disablities' %>
					</th>
				</tr>
				<tr>	
					<td>
						<%= f.check_box :recruiter %>
					</td>
					<td>
						<%= f.check_box :internship %>
					</td>
					<td>
						<%= f.check_box :non_profit %>
					</td>
					<td>
						<%= f.check_box :telecommuting %>
					</td>
					<td>
						<%= f.check_box :disability %>
					</td>
				</tr>
				
			</table>
			
			
	</div>
	<div class="row">
		<div class="col-md-3"></div>
	      <div class="form-group col-md-6">
	        <%= f.label :salary, :class => 'sr-only', :for => 'exampleInputSalary3' %>
	        <%= f.text_field :salary, :class => 'form-control', :id => 'exampleInputSalary3', :placeholder => 'Payment - Be as Specific as Possible' %>
	      </div>
	</div>
</div>

app/views/items/edit.html.erb
<div class="category-holder">
	<h2>Edit your Item</h2>
</div>

<%= render 'form' %>

<%= link_to 'Back', @item %>

app/views/items/filter.html.erb
<% @listofitems.each do |item| %>
  
  <ul>
    <li>
      <ul>

        <li><a href="/items/<%= item.item_id %>"><%= item.name %></a></li>
        <li><%= item.created_at.strftime "%e %B, %Y" %></li>
      </ul>
    </li>
  </ul>

  <% end %>

app/views/items/index.html.erb
<div class="category-holder">
	<h2>My Items</h2>
</div>
<div class="listing">
	<ul>
		<li>
			<ul>
				<% @items.each do |item| %>
					
					
						<div id="item-container" class="col-md-3">
							<li class="image-container">
								<%= link_to(cl_image_tag(item.image), item) %>
							</li>
							<li class="description-container">
								<%= item.name %>
							</li>
							<li class="description-container">
								<%= item.created_at.strftime "%e %B, %Y" %>
							</li>
							
						</div>
					
					
				<% end %>
			</ul>	 
		</li>

	</ul>

</div>

app/views/items/show.html.erb
<div class="item-holder">
  <h3><%= @item.name %></h3>
</div>
<div class="item">
  <% if @current_user.present? %>


    <p id="notice"><%= notice %></p>


    <div id="currentItemID" style="display:none"><%= @item.id %></div>
    <%# Will show if the category is For Sale %>
    <% if @item.subcategory.category.name == 'for sale' %>

    <%# Will show if the subcategory is for cars+trucks/motorcycles/rvs+camp %>
    <p>
      <span id="show"><strong>Description:</strong> <%= @item.make %></span> <span id="show"><%= @item.make_type %></span> <span id="show"><strong>Year:</strong> <%= @item.make_year %></span>
    </p>
      
    <p>
      <span id="show"><strong>Transmission:</strong> <%= @item.transmission %></span>  <span id="show"><strong>Type:</strong> <%= @item.car_type %></span> <span id="show"><strong>Distance Travelled (km):</strong> <%= @item.odometer %></span>
    </p>
    <p>
      <span id="show"><strong>Fuel:</strong> <%= @item.fuel %></span>
    </p>

    <%# will show if subcategory is motorcycles %>
    <p>
      <span id="show"><strong>Engine Displacement (CC): </strong> <%= @item.engine_displacement %></span>
    </p>

    <%# will show if subcategory is boats %>
    <p>
      <span id="show"><strong>Propulsion Type: </strong> <%= @item.propulsion_type %></span> <span id="show"><strong>Length Overall (LOA)</strong> <%= @item.length_overall %></span>
    </p>

    <%# will show if subcategory is mobile phones %>
    <p>
      <span id="show"><strong>Operating System: </strong> <%= @item.mobile_os %></span>
    </p>

    <% end %>

    <%# Will show if the category is Housing %>
    <% if @item.subcategory.category.name == 'housing' %>
    <p>
      <span id="show"><strong>Type:</strong> <%= @item.housing_type %></span> <span id="show"><strong>Room(s):</strong> <%= @item.rooms %></span><span id="show"><strong>Bathroom(s):</strong> <%= @item.bathrooms %></span>
    </p>
    <% end %>

    <%# Will show if the category is Jobs %>
    <% if @item.subcategory.category.name == 'jobs' %>
    <p>
      <span id="show"><strong>Employment Type: </strong><%= @item.employment_type %></span><span id="show"><strong>Salary: </strong><%= @item.salary %></span>
    </p>
    <% end %>

    <% if @item.image %>
      <p><%= cl_image_tag(@item.image, :width=>200, :crop=>:thumb, :gravity=>:face, :effect=>"vibrance") %></p> 
    <% end %>

    <p>
      <strong>Description:</strong><span><%= @item.description %></span>
      
    </p>

    <% if @item.subcategory.category.name == 'housing' %>
      <p>
        <span id="show"><strong>Rent (per week):</strong>  <%= number_to_currency(@item.rent) %></span> <span id="show"><strong>Area (m2):</strong> <%= @item.area %></span> <span id="show"><strong>Available from:</strong> <%= @item.available %></span>
      </p>

      <p>
        <span id="show"><strong>Room:</strong> <%= @item.private_room %></span> <span id="show"><strong>Bathroom:</strong> <%= @item.private_bathroom %></span> <span id="show"><strong>Laundry:</strong> <%= @item.laundry %></span> <span id="show"><strong>Parking:</strong> <%= @item.parking %></span>
      </p>


      <p>
        <% if @item.pets? %>
          <strong>Pets:</strong> <i class="icon-dog"></i><i class="icon-cat"></i>
        <% end %>
        <% if @item.smoking? %>
          <strong>Smoking:</strong> <i class="icon-cigarette"></i>
        <% end %>
        <% if @item.furnished %>
          <strong>Furnished:</strong> <i class="icon-chair"></i>
        <% end %>
        <% if @item.wheelchair %>
          <strong>Wheelchair Accessible:</strong> <i class="icon-wheelchair"></i>
        <% end %>
      </p>

      <p>
        <% if @item.openhouse1? %>
          <ul>
            <li><%= @item.openhouse1 %></li>
            <li><%= @item.openhouse2 %></li>
            <li><%= @item.openhouse3 %></li>
          </ul>
        <% end %>
      </p>
    <% end %>

    <% if @item.subcategory.category == 'jobs' %>
      <% if @item.recruiter? %>
        <strong>Direct Contact by Recruiters: </strong><i class="icon-ok"></i>
      <% end %>
      <% if @item.internship? %>
        <strong>Internship:</strong> <i class="icon-ok">
      <% end %>
      <% if @item.non_profit? %>
        <strong>Non-profit Organisation:</strong> <i class="icon-ok"> 
      <% end %>
      <% if @item.telecommuting? %>
        <strong>Telecommuting permissible:</strong> <i class="icon-ok">
      <% end %>
      <% if @item.disability? %>
        <strong>Open for People with Disabilities:</strong> <i class="icon-ok">
      <% end %>
    <% end %>


    <% if @item.price? %>
      <p>
      <strong>Price:</strong>
      <%= number_to_currency(@item.price) %>
      </p>
      <% if @item.price < 5000 && @current_user != @item.user %>
        <%= form_tag buy_path(id: @item.id) do %>
        <script
            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-amount="<%= @item.price * 100 %>"
            data-name="VDM"
            data-description="<%= @item.name %>"
            data-email="<%= @current_user.email %>">
          </script>

        <% end %>
      <% end %>


    <% end %>

    <% if @item.subcategory.category.name == 'for sale' %>
      <p>
        <span id="show"><strong>Dimensions: </strong> <%= @item.dimensions %></span> <span id="show"><strong>Serial Number:</strong> <%= @item.serial_number %></span> <span id="show"><strong> VIN:</strong> <%= @item.vin %></span>
      </p>
      <p>
        <span id="show"><strong>Colour:</strong> <%= @item.paint_colour %></span>
      </p>
      <p>
        <span id="show"><strong>Title Status: </strong> <%= @item.title_status %></span>
      </p>
      <p>
        <% if @item.garage_sale1? %>
          <ul>
            <li> Garage sale dates:
              <ul>
                <li><%= @item.garage_sale1 %></li>
                <li><%= @item.garage_sale2 %></li>
                <li><%= @item.garage_sale3 %></li>
              </ul>
            </li>
          </ul>
        <% end %>
      </p>
      <p>
        <span id="show"><strong>Starts:</strong> <%= @item.start_time %></span>
      </p>
      <p>
        <span id="show"><strong>Venue:</strong> <%= @item.venue %></span>
      </p>
      <p>
        <span id="show"><strong>Number of Tickets: </strong> <%= @item.tickets %></span>
      </p>
      <p>
        <span id="show"><strong>When's it on?</strong> <%= @item.event %></span>
      </p>
    <% end %>



    <p>
      <strong>Category:</strong>
      <%= @item.subcategory.category.name %>
    </p>

    <p>
      <strong>Subcategory:</strong>
      <%= link_to @item.subcategory.name, subcategory_path(@item.subcategory) %>
    </p>

    <p>
      <strong>User:</strong>
      <%= @item.user.name %>
    </p>

    <p>
      <strong>Posted:</strong>
      <%= @item.created_at.strftime "%e %B, %Y" %>
    </p>

    <% if (@current_user == @item.user) %>

      <%= link_to 'Edit', edit_item_path(@item) %>

      <%= link_to 'Delete Item', @item, :method => 'delete', :data => {:confirm => "Are you sure you want to delete this?"} %>

    <% else %>


      <p>Contact: <%= link_to @item.user.email, new_conversation_path(:recipient_id => @item.user.id, :subject => @item.name) %></p>

    <% end %>

  <%= form_for Bookmark.new do |f|  %>

  <%= f.hidden_field :item_id, value: @item.id %>
  <%= f.hidden_field :user_id, value: @current_user.id %>

  <%= f.submit "bookmark this" %>
  <% end %>

        <script src="https://maps.googleapis.com/maps/api/js"></script>
        <script>
          function initialize() {
            var mapCanvas = document.getElementById('map');
            var mapOptions = {
              center: new google.maps.LatLng(-33.7969235,150.9224326),
              zoom: 8,
              mapTypeId: google.maps.MapTypeId.ROADMAP
            }
            var map = new google.maps.Map(mapCanvas, mapOptions)

            var locations =[]
            locations.push({name:"Home", latlng: new google.maps.LatLng( <%= @current_user.latitude %>,<%= @current_user.longitude %>)});
            locations.push({name:"<%= @item.name %>", latlng: new google.maps.LatLng(<%= @item.latitude %>, <%= @item.longitude %>)});
            
            var bounds = new google.maps.LatLngBounds ();
            for(var i = 0 ; i<locations.length ; i++){
              var marker = new google.maps.Marker({position:locations[i].latlng, map:map, title:locations[i].name})
              bounds.extend (locations[i].latlng)
            }
            map.fitBounds(bounds)
          }
          google.maps.event.addDomListener(window, 'load', initialize);
        </script>

      <% unless @current_user.id == @item.user_id %>
          <div id="map"></div>
      <% end %>
      
  <% else %>

    <p>You need to have an account to view a post.</p>
    <p>Please <%= link_to 'Sign In', login_path %>, or <%= link_to 'Create an Account', new_user_path %>.</p>

  <% end %>
</div>
  