config/routes.rb
Rails.application.routes.draw do
  get '/categories/home' => 'categories#home'
  root :to => 'categories#home'


  post '/items/nearme' => 'items#nearme'
  get '/items/filter' => 'items#filter'

  get '/categories/api' => 'categories#api'
  get '/bookmarks/api' => 'bookmarks#api' 
  get '/items/api' => 'items#api'

  post '/buy/:id', to: 'transactions#create', as: :buy
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

  resources :wishes

  resources :bookmarks

  resources :items do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  
  resources :categories do 
    collection do
      get 'search'
    end
  end

  resources :subcategories
  get "mailbox/api" => "mailbox#api"
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
      member do
          post :reply
          post :trash
          post :untrash
      end
  end
  get '/session' => 'session#show'
  get '/login' => 'session#new'
  get '/session' => 'session#show'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  
  resources :users


  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VDMApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div><img id="logo" src="<%= image_path 'VDM.png' %>"></div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= categories_home_path %>">Categories</a></li>
        <li><a href="<%= new_item_path %>">Post</a></li>
        <li><a href="<%= new_wish_path %>">Make a Wish</a></li>
        
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>


      <%= form_tag search_items_path, method: :get, class: "navbar-form navbar-left", role: "search" do %>
        <div>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <% if @current_user.present? %>
        	<li class="active"><a href="<%= user_path(@current_user) %>"><%= @current_user.name %><span class="sr-only">(current)</span></a></li>
          <li><%= link_to mailbox_inbox_path do  %>
              <span>Inbox</span> <span class="label label-danger"><%=unread_messages_count%></span>
            <% end %>
          </li> 
        <li class="dropdown">
          		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Options<span class="caret"></span></a>
          		<ul class="dropdown-menu">
            		<li><a href="<%= edit_user_path(@current_user) %>">Edit Details</a></li>
            		<li><a href="<%= items_path %>">My Items</a></li>
            		<li><a href="<%= wishes_path %>">Wish List</a></li>
            		<li><a href="<%= bookmarks_path %>">Bookmarks</a></li>
            		<li><a href="<%= mailbox_inbox_path %>">Inbox</a></li> 
            		<li><%= link_to 'Log out', login_path, :method => 'delete', :data => {:confirm => 'Are you sure you wish to log out?'} %></li>
          		</ul>
        	</li>
        <% else %>
        	<li class="active"><a href="<%= login_path %>">Sign In<span class="sr-only">(current)</span></a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<script type="text/template" id="PingViewTemplate">
  {{}}
</script>


<div class="container">
  <%= yield %>
</div>


</body>
</html>